### ISSUE TITLE
Can you explain the output of the example code?

### ISSUE THREAD

**Issue by danhardman** [aaparella/drago#1]
I'm a bit confused with the outputs I'm getting from the example code. I would have expected single classifier outputs based on the inputs but I fear I don't understand what's being inputted into the learn function.

Is this right?

```
net.Learn([][][]float64{
    {{variable1, variable2}, {class}},
})
```

If so, why isn't the prediction output a predicted class?

**Comment by aaparella** [comment]
The network won't predict discrete classes, the example provided just happened to have two values for the predicted label. I'll add more examples with continuous labels to clarify this. 

Let me know if I'm not getting your question.

**Comment by danhardman** [comment]
More examples would be brilliant. I think I'm gonna have to do more research on ANNs before I come back to this as it's still not clear. 

By label, do you mean class?
