### ISSUE TITLE
Error values are way high

### ISSUE THREAD

**Issue by danhardman** [aaparella/drago#2]
Is the network.currentErr value the average error? If not can we make it exported so we can calculate the current error of the network? 

I'm getting error values like `154.8035667621243` after 10000 iterations.

**Comment by aaparella** [comment]
It isn't, it's used strictly for calculations. Can I see how you're using the network?

**Comment by danhardman** [comment]
```
func main() {
    net := Drago.New(.1, 10000, []int{3, 5, 5, 1}, []Drago.Activator{new(Drago.Sigmoid), new(Drago.Sigmoid)})
    //net.Verbose = false
    samples := [][][]float64{
        {{20.937, 6.17, 22.792}, {6.42501}},
        {{20.375, 5.27, 20.5631}, {0.505808}},
        {{20.625, 5.27, 21.569}, {1.90032}},
        {{20.562, 5.27, 22.8776}, {6.343}},
        {{20.187, 5.27, 22.7772}, {6.58899}},
        //Lots more data
    }
    net.Learn(samples)
    fmt.Println(net.Predict([]float64{20.937, 6.17, 22.792}).At(0, 0))
}
```

**Comment by aaparella** [comment]
How many samples would you say you have, roughly? If you have an appreciable number, you should set the number of iterations far far lower, try 25 or something in that ballpark. Iterating 10000 times will lead to extreme overfitting, and negatively impact your results.

**Comment by danhardman** [comment]
Really wouldn't have expected that, typically you want a lot of iterations surely? Is this set up different to others I'm likely to have used? Being feed forward maybe? I have 50 samples.

**Comment by aaparella** [comment]
If you have too many iterations, you will overfit to the dataset that you trained on, and will get poor results when you are predicting values that were not in your original dataset. You can also experiment with different topologies / learning rates / numbers of iterations to see what will give you the best results. Also, getting more data samples would help, 50 is very few.
